name: Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    name: Run validations
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dotnet tools
        run: dotnet tool restore

      - name: Verify formatting
        run: dotnet tool run dotnet-format --verify-no-changes blog.sln

      - name: Restore solution
        run: dotnet restore blog.sln

      - name: Build solution
        run: dotnet build blog.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test blog-tests/blog-tests.csproj --no-restore --no-build --configuration Release
